# Generated by Django 5.1.15 on 2026-06-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cvuploadrecord",
            name="cv_summary",
            field=models.TextField(blank=True, default=""),
        ),
    ]
